### PR TITLE
google calendar integration

### PR DESCRIPTION
**Pull request by EbonyLouis**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Adding google calendar integration. 
Working on adding event images, since our google drives don't allow public urls, and we're using netlify functions it's going to be a bit more tricky. I want to get this out at least and then will circle back with images

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by angiejones** [comment]
@EbonyLouis I don't see it on the [deploy preview](https://deploy-preview-958--tbd-website-developer.netlify.app/community). It says "Error: Failed to fetch"

**Comment by EbonyLouis** [comment]
@angiejones it's good now, my last push was just so nick could help me through a react versioning issue

**Review by dayhaysoos — APPROVED** [review]
Overall, this looks good to me! If I were to nit pick anything:

- Most of the styling we have done on the site is tailwind. I don't mind leaving the styles the way you set them up here since they pertain only to this component
- Some styles are done within separate objects, where others are done inline. Fine with me, as long as it works, but just want to call out the inconsistency there.

There also seems to be a lot of content changes on other, unrelated files. Not sure if that was intentional or not. If you're aware of those changes then that's fine. I think merging would be okay regardless, but it's something to keep in mind for your next PR.

**Comment by EbonyLouis** [comment]
@dayhaysoos For styling since I was constantly updating it to get it how I wanted. It was easier for me personally to track and update when I had everything there in those objects. That's why its so inconsistent lol however it is noted thank you for reviewing it.

**Pull request merged**
