### PR TITLE
0.7.11 Web5 Update to docs

### PR DESCRIPTION
**Pull request by bobbilee19**

### CODE REVIEW

**Comment by bobbilee19** [comment]
I do also see in Web5 API Reference...should we be updating these versions? 
- https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L44
- https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L50
- https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L70
- https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L76

**Comment by angiejones** [comment]
> I do also see in Web5 API Reference...should we be updating these versions?
> 
> * https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L44
> * https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L50
> * https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L70
> * https://github.com/TBD54566975/developer.tbd.website/blob/issue-583/update-web5-v/site/api/web5-js/index.mdx#L76

yes

**Comment by angiejones** [comment]
Quickstart also still shows 7.10 here

image

**Review by angiejones — CHANGES_REQUESTED** [review]
Need to change version on Quickstart page and also on API reference guide

**Comment by bobbilee19** [comment]
I searched for everywhere it's found and changed, so looking back now and seeing what's going on.

**Review by angiejones — APPROVED** [review]

**Pull request merged**
