### PR TITLE
video-card fixed

### PR DESCRIPTION
**Pull request by Pratham271**
## What type of PR is this? (check all applicable)
#913 
- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by EbonyLouis — APPROVED** [review]

**Comment by EbonyLouis** [comment]
@Pratham271 Thank you ! 🥳

**Comment by angiejones** [comment]
@Pratham271 thanks for the fix. the code is duplicated each time we add a video. do you want to open another issue to make your changes standardized in the [Video component](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/src/components/Video.jsx) and then use the `<Video>` component in the blog posts? that would be an amazing contribution

**Comment by Pratham271** [comment]
Yess should I open a new one

**Comment by EbonyLouis** [comment]
@Pratham271 yes you can open a new PR thanks!

**Pull request merged**
