### PR TITLE
Add styling to search widget 

### PR DESCRIPTION
**Pull request by kirahsapong**
Adds styling to search widget to add 
- list numbering
- list bullets
- paragraph spacing
- more prominent label heading
Screenshot 2023-07-27 at 3 55 40 PM

### CODE REVIEW

**Review by ALRubinger — CHANGES_REQUESTED** [review]
Thanks @kirahsapong! Looking awesome already!

Could we make it support longer inputs so the user can read the full thing? Maybe textbox that grows as input does?

image

**Review by ALRubinger — APPROVED** [review]
DOPE.

LGTM.

**Comment by michaelneale** [comment]
@ALRubinger how do I get access to the vercel preview app?

**Review by michaelneale — CHANGES_REQUESTED** [review]
when I press enter - it adds a new line and then runs the chat, which looks a bit odd: 

image could it not add the newline on Enter?

**Comment by ALRubinger** [comment]
@michaelneale - we're still on Netlify; Vercel is a temp backup we can roll over to if necessary. @kirahsapong's deploy preview is here from the Netlify bot - https://github.com/TBD54566975/developer.tbd.website/pull/618#issuecomment-1654708322

**Review by michaelneale — APPROVED** [review]

**Pull request merged**
