### PR TITLE
fix: Fix the broken Twitter `follow` button

### PR DESCRIPTION
**Pull request by mathieurivest**
# Overview

Fixes the broken Twitter `Follow` button on the [community](https://developer.tbd.website/open-source/contributing/) page.

# Details

Changes it from https://twitter.com/TBDDev which does not seem to exist to https://twitter.com/TBDevs which does exists.

### CODE REVIEW

**Comment by michaelneale** [comment]
good catch @mathieurivest  - should it be https://twitter.com/TBDevs?

**Comment by mathieurivest** [comment]
> good catch @mathieurivest - should it be https://twitter.com/TBDevs?

Oooh! It should indeed! Thanks for catching this, will be way more relevant! 😊

**Comment by michaelneale** [comment]
LGTM

@dayhaysoos - can we fix those netlify problems?

**Comment by dayhaysoos** [comment]
> LGTM
> 
> @dayhaysoos - can we fix those netlify problems?

Bout to look into it now!

**Comment by dayhaysoos** [comment]
Ah, the issue was a weird joi schema versioning thing under the hood of docusaurus. This came up after the pnpm switch (and a minor upgrade). Clearing cache and rebuilding is the fix, here's the log for the successful build:

https://app.netlify.com/sites/tbd-website-developer/deploys/64a8115e5713d10bcfffa2bc


Gonna go ahead and merge this now. Thank you @mathieurivest !!

**Pull request merged**
