### PR TITLE
Issue #562 - Add Datadog analytics scripts

### PR DESCRIPTION
**Pull request by ALRubinger**
For Issue #562 

@dayhaysoos  - would you review this is where you'd expect us to put scripts that we want to fire on every page?

Let's hold on merging this until we confirm that the tracking is making it into the analytics Dashboard. Looks like it might be, based on traffic:

image

### CODE REVIEW

**Comment by ALRubinger** [comment]
Confirmed this is piping through to Datadog:

image

Moving this from `DRAFT` PR into a real PR for @dayhaysoos +1 and rebase/merge

**Comment by dayhaysoos** [comment]
Gonna take a look at this later today

**Review by dayhaysoos — APPROVED** [review]
LGTM

**Comment by ALRubinger** [comment]
Upstream in 2f2be8a

**Pull request closed without merging**
