### PR TITLE
Update redirect config to new blog location

### PR DESCRIPTION
**Pull request by ALRubinger**
#387

@angiejones does this satisfy what you're requesting? If not, where is the "old" link you're referring to in #387?

Pending @angiejones review, leaving to @dayhaysoos to field the PR and merge alongside the other work flowing in for Phase 2.

### CODE REVIEW

**Review by angiejones — COMMENTED** [review]
yes but it needs to be merged as part of phase-2 as thats where the changes are

**Comment by dayhaysoos** [comment]
We should probably add a Redirect on Netlify config just in case anyone tries to access the old link, yeah? If I remember correctly, this blog was announced and shared publicly

**Comment by dayhaysoos** [comment]
Oh just found there was an issue for this #387, going to check now

**Review by dayhaysoos — APPROVED** [review]

**Comment by dayhaysoos** [comment]
I'm going to make sure this gets into main

**Review by angiejones — COMMENTED** [review]
from should be: /docs/tutorials/issue-verifiable-credential-manually/

**Pull request merged**
