### PR TITLE
Removing optional `externalId` from Swift snippets

### LINKED ISSUE #1350: Remove `externalID` from Swift messages
After https://github.com/TBD54566975/tbdex-swift/issues/71 is fixed, update Swift guides to remove `externalID` from the messages

### PR DESCRIPTION
**Pull request by angiejones**
## What type of PR is this? (check all applicable)

- [X] 📝 Documentation Update

## Description

Removed nil `externalId` property from Swift messages

## Related Tickets & Documents

Resolves #1350 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206921594576825

### CODE REVIEW

**Review by acekyd — APPROVED** [review]

**Comment by acekyd** [comment]
LGTM! But there seems to be an error with the package.resolved.

**Review by blackgirlbytes — APPROVED** [review]
I tried it out! Seems good to me. I wasn't able to repro the issues Ace is seeing with the Package.resolved

**Comment by angiejones** [comment]
> LGTM! But there seems to be an error with the package.resolved.

re-ran and it's passed now

**Review by EbonyLouis — APPROVED** [review]
🥳

**Pull request merged**
