### PR TITLE
Incubation page

### PR DESCRIPTION
**Pull request by Pratham271**
#746 

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by angiejones** [comment]
@EbonyLouis can you review this one?
https://deploy-preview-951--tbd-website-developer.netlify.app/community/incubation-projects/

**Review by EbonyLouis — COMMENTED** [review]
From what I remember weren't you going to use the video component?

**Comment by Pratham271** [comment]
But this is the incubation highlights page what's the use of video in this, the video was for video card issue

**Comment by EbonyLouis** [comment]
@Pratham271 you have the video code in this PR if you remove the blog files I can approve this PR. 

I love the way you incorporated the incubation highlights page it'll make it super easy to add more projects in the future.- thanks

**Comment by Pratham271** [comment]
I have removed the blog files now, and I am glad that you loved the work.
welcome

**Comment by EbonyLouis** [comment]
@Pratham271 it says the files were deleted, we don't want to push that do you mind reversing the changes and not including the blog pages in the PR?

**Comment by EbonyLouis** [comment]
@Pratham271 Hey can you remove the blogs from this PR please, so I can close it out?

**Pull request merged**
