### PR TITLE
New API Documentation

### PR DESCRIPTION
**Pull request by dayhaysoos**
Breaking this branch off for @chris-tbd  to start experimenting with styling and content organization under API reference.

In the mean time, I'm going to experiment with how far I can get with Docusaurus' `sidebarItemsGenerator`:

https://docusaurus.io/docs/sidebar/autogenerated#customize-the-sidebar-items-generator

The goal is to allow us to have full control over what gets populated in the sidebar. As of right now we're getting anything and everything under the `/docs/api` directory.

This is for issue #436

### CODE REVIEW

**Comment by ALRubinger** [comment]
Will need to rebase atop `phase-4` to see the true latest and resolve merge conflicts

**Comment by chris-tbd** [comment]
Adding @frankhinek for content review

**Comment by ALRubinger** [comment]
Descoping off Phase 4; can be fast follow by Saturday per @chris-tbd @csuwildcat

**Comment by chris-tbd** [comment]
Rebased, could I get reviews @angiejones @ALRubinger @csuwildcat

**Review by ALRubinger — CHANGES_REQUESTED** [review]
Two changes requested:

1) Build failing per Netlify - @chris-tbd you can confirm these are clean locally by running `npm run build` to trigger the same production build that Netlify does. It shows:

```
9:46:15 AM: [ERROR] Unable to build website for locale en.
9:46:15 AM: [ERROR] Error: Docusaurus found broken links!
9:46:15 AM: 
9:46:15 AM: Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
9:46:15 AM: Exhaustive list of all broken links found:
9:46:15 AM: 
9:46:15 AM: - On source page path = /api/web5-js/dwn/:
9:46:15 AM:    -> linking to permissions.mdx (resolved as: /api/web5-js/dwn/permissions.mdx)
9:46:15 AM: 
9:46:15 AM:     at throwError (/opt/build/repo/node_modules/@docusaurus/logger/lib/index.js:76:11)
9:46:15 AM:     at handleBrokenLinks (/opt/build/repo/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
9:46:15 AM:     at async buildLocale (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:186:5)
9:46:15 AM:     at async tryToBuildLocale (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:41:20)
9:46:15 AM:     at async mapAsyncSequential (/opt/build/repo/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
9:46:15 AM:     at async Command.build (/opt/build/repo/node_modules/@docusaurus/core/lib/commands/build.js:76:21)
9:46:15 AM: [INFO] Docusaurus version: 2.4.0
9:46:15 AM: Node version: v18.15.0
9:46:15 AM: ​
9:46:15 AM: "build.command" failed                  
```

2) Still some merge conflicts with `main`.

**Review by ALRubinger — CHANGES_REQUESTED** [review]
1) Still getting "unable to rebase due to conflicts"

2) Selected items  like `web5.js`, `did` in navbar become hidden due to same bg and fg color: 

image

3) Can right navbar always be in view? Right now it scrolls down with the page:

image

4) On the Docs NavBar, `Web5 SDK` is its own top-level item, linking to the existing Markdown file that this PR is to replace?

image

**Comment by angiejones** [comment]
> 1. Still getting "unable to rebase due to conflicts"
> 2. Selected items  like `web5.js`, `did` in navbar become hidden due to same bg and fg color:
> 
> image
> 3. Can right navbar always be in view? Right now it scrolls down with the page:
> 
> image
> 4. On the Docs NavBar, `Web5 SDK` is its own top-level item, linking to the existing Markdown file that this PR is to replace?
> 
> image

That navbar item should be deleted. I was immediately confused by what it was seeing as there's already a Web5 JS menu item.

What we could do instead is add a "API Docs" menu item under Web5 JS like this:
image

**Comment by dayhaysoos** [comment]
@ALRubinger @angiejones as far as some of the styling changes, not all of Kirah's styles are being applied here. Should be some minor adjusting.

I'm going to work on that first and then move on to the navbar items feedback.

**Comment by ALRubinger** [comment]
Latest review from recent pushes:

* I still see "This branch cannot be rebased due to conflicts" - I'm available to help with rebasing and getting a clean merge atop `main`, @dayhaysoos.

* Sidebar on docs still has a duplicate "Web5 JS SDK" link:
image

See @angiejones note above:

> That navbar item should be deleted. I was immediately confused by what it was seeing as there's already a Web5 JS menu item.
> What we could do instead is add a "API Docs" menu item under Web5 JS like this:

* Right sidebar on the API Docs still scrolls down with page instead of being locked to the top

**Comment by angiejones** [comment]
> Latest review from recent pushes:
> 
> * I still see "This branch cannot be rebased due to conflicts" - I'm available to help with rebasing and getting a clean merge atop `main`, @dayhaysoos.
> * Sidebar on docs still has a duplicate "Web5 JS SDK" link:
> 
> image
> See @angiejones note above:
> 
> > That navbar item should be deleted. I was immediately confused by what it was seeing as there's already a Web5 JS menu item.
> > What we could do instead is add a "API Docs" menu item under Web5 JS like this:
> 
> * Right sidebar on the API Docs still scrolls down with page instead of being locked to the top

I'm not talking about a styling issue. I'm asking to delete the last menu item here

**Comment by ALRubinger** [comment]
@angiejones wrote:

> I'm not talking about a styling issue. I'm asking to delete the last menu item here

Yep - there's two things I'm flagging. One is as you mention, asking to delete "Web5 JS SDK" from the Docs Left Sidebar.

The other is the right sidebar on the API Reference; it scrolls partially out of view as you scroll down the page.

**Comment by dayhaysoos** [comment]
Yeah I didn't address angie's feedback in the last commit, I did what she asked locally, looking into the scrolling now. I guess I wasn't ready for review on that last commit, I was just putting it out there in the meantime

**Comment by dayhaysoos** [comment]
I've prevented the scrolling up that happens on table of content bar on the right, I've also applied Kirah's styling to it so it's consistent across the board. Ready for review now @ALRubinger

**Pull request merged**
