### PR TITLE
[Hacktoberfest] Create Your Own TikTok Video About VCs

### LINKED ISSUE #1731: Create Your Own TikTok Video About Verifiable Credentials (VCs)
# Create Your Own TikTok Video About VCs

## 🚀 Goal
Create your own TikTok video about verifiable credentials (VCs) on your own channel.

## 🤔 Background
This issue focuses specifically on spreading more awareness about VCs. Your contributions here will help you spread your knowledge across the web and to our community!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own TikTok channel.
- [ ] The content submitted for this task can be cross-posted across other platforms, however it will only count towards one content task. You may not reuse your content submitted for this task to get points for another task unless there are significant changes (like adding 30 seconds of extra content on YouTube).
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources

- https://developer.tbd.website/docs/web5/verifiable-credentials/what-are-vcs
- https://developer.tbd.website/docs/web5/verifiable-credentials/fan-club-vc
- https://developer.tbd.website/blog/7-ways-we-use-vcs-today
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

### PR DESCRIPTION
**Pull request by breehall**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [X] 🚩 Other - Hacktoberfest

## Description
This PR adds an entry inside of `externalContributors.json` which links to a TikTok I created on VCs for Hacktoberfest

## Related Tickets & Documents
Resolves #1731 

## Mobile & Desktop Screenshots/Recordings
N/A

## Added code snippets?
- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed

## Added tests?
- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [X] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?
Spongebob & Patrick

### CODE REVIEW

**Comment by taniashiba** [comment]
Your video came out amazing! Thank you so much! We'll be sure to review/merge ASAP 🖤

**Review by blackgirlbytes — CHANGES_REQUESTED** [review]
Hi @breehall! I love your video. My team is raving about it in Slack. Your thumbnail isn't showing up because you need to add a / in front of the word img so it can get the correct path. And this is a nitpick, but do you mind switching the type to say video instead of social? After that, i can merge and approve.

**Comment by EbonyLouis** [comment]
@breehall no everything is great! Sometimes that test is finicky and we need to rerun it a few times. Your video is so great it inspires me to be a little bit more creative with my shorts.

**Review by blackgirlbytes — APPROVED** [review]
yay! thank you!

**Pull request merged**
