### PR TITLE
fixed align arrow in mobile version

### PR DESCRIPTION
**Pull request by captain-Akshay**
### Current state

fixes issue  #772
image

### Fixed state 

image

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR fixes this bug. 

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [] 📓 general documentation
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by angiejones** [comment]
here's what I'm seeing on the [deploy preview](https://deploy-preview-784--tbd-website-developer.netlify.app/)
image

**Review by angiejones — CHANGES_REQUESTED** [review]
can you double check on the deploy preview?

**Comment by captain-Akshay** [comment]
@angiejones My apologies. Here are the revised changes.

**Review by EbonyLouis — APPROVED** [review]
looks good!

**Pull request merged**
