### PR TITLE
guide on sending records

### PR DESCRIPTION
**Pull request by angiejones**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [✅] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
This PR adds a new guide on sending records

## Added code snippets?
- [✅] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [✅] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [✅] 📓 general documentation
- [ ] 🙅 no documentation needed

## What gif best describes this PR or how it makes you feel?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205206526606808

### CODE REVIEW

**Comment by angiejones** [comment]
Here is the [preview](https://deploy-preview-837--tbd-website-developer.netlify.app/docs/web5/build/decentralized-web-nodes/send)

@diehuxx please review for accuracy.
@blackgirlbytes @acekyd please make sure it's crystal clear. If anything is fuzzy, please call it out so I can make it clearer

**Comment by acekyd** [comment]
Everything seems clear @angiejones. 

On a side note, I always assumed we have to write to a recipient's remote DWN before sync fetches and updates locally for them. This guide indicates that we can send directly to their local DWN, but what's the behaviour / error if the recipient is offline at the time? Does it send to their remote DWN pending connection? cc @diehuxx

**Review by acekyd — APPROVED** [review]

**Comment by blackgirlbytes** [comment]
Love it! This was super clear to me. I've only had one question, which doesn't need to be included in your guide..but I'm just curious..why do we have a `records.write()` method and a `records.create()` method

**Review by blackgirlbytes — APPROVED** [review]

**Comment by angiejones** [comment]
> Love it! This was super clear to me. I've only had one question, which doesn't need to be included in your guide..but I'm just curious..why do we have a `records.write()` method and a `records.create()` method. I know that write is an alias for create, but why did we make the choice to have both

it was `write` before but then we realized that CRUD indicates `create`, so we added it as an alias just in case people's mind goes there first

**Comment by angiejones** [comment]
Related issue: https://github.com/TBD54566975/dwn-sdk-js/issues/550

**Pull request merged**
