### PR TITLE
Solved issue #745

### LINKED ISSUE #745: Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```

There are two of these errors on the following page: `/docs/web5/quickstart`

Just need to address the nesting issues. This page could be a little weird as it's broken up into MDX components in a js file, so please let me know if you need some guidance.

### PR DESCRIPTION
**Pull request by Kabewh**
deleted unnecessary `<p>` tags to fix #745

### CODE REVIEW

**Comment by angiejones** [comment]
@dayhaysoos how do I recreate this error? Just went through the Quickstart (before this fix is deployed) and I don't see these errors in the console

**Comment by Kabewh** [comment]
I can help with that, in order to recreate this error, after you run 'pnpm start' and the website opens, on the website you must navigate to the quickstart page.

**Comment by EbonyLouis** [comment]
Hi @Kabewh, thank you for working on this. I'd also like to note that Hacktoberfest officially kicks off on **October 1st**. Contributions made before the event may not be eligible for the challenge. **If you want this to count towards Hacktoberfest's official prizes**, we can hold off on merging.  Let me know what you would like to do. 

> to be eligible for Hacktoberfest's official prizes please make sure you're registered, registration [opens September 26th.](https://hacktoberfest.com/)

**Comment by Kabewh** [comment]
Hi @EbonyLouis thanks for info, I'll wait so that this will count towards hacktoberfest.

**Comment by angiejones** [comment]
> I can help with that, in order to recreate this error, after you run 'pnpm start' and the website opens, on the website you must navigate to the quickstart page.

hey I did this and ran all the steps in the quickstart but my Error log in the console is clean
image

**Comment by angiejones** [comment]
Even without pulling down this change, I'm not able to reproduce locally. @dayhaysoos can you verify that this fixes the issue you were seeing?

**Review by dayhaysoos — APPROVED** [review]

**Comment by dayhaysoos** [comment]
Can confirm before pulling errors were still there. This PR fixes them for the quickstart page and the "create a did" page.

@EbonyLouis

**Pull request merged**
