### PR TITLE
Set up feedback widget

### PR DESCRIPTION
**Pull request by dayhaysoos**
Creating this PR to get feedback early. This is currently how the feedback widget looks below:

Screenshot 2023-05-08 at 4 21 24 PM

**Note**

It's missing the "Edit This Page" links because it's been a bit harder getting those URLs than I expected. For the sake of moving forward I'd love to get this widget merged ASAP and make a new ticket for solving that editUrl issue.

Would like feedback from @EbonyLouis @bobbilee19 @kirahsapong

### CODE REVIEW

**Comment by ALRubinger** [comment]
@dayhaysoos Thanks!

Can we have it float in a minimized mode so it's always visible in the bottom right, rather than pinned to the bottom of the page. And on expand, shows as you have it here?

**Comment by dayhaysoos** [comment]
@ALRubinger  I'm not sure if that makes for the best docs experience. Normally, those types of pop ups are designed for marketing or sales engagements and I personally feel like I'd be annoyed by seeing something like that floating on the page.

I don't think I've ever seen Docs do something like that either, normally feedback options or surveys are at the bottom.

I also think we should get @EbonyLouis opinion on this because she was expecting something at the bottom:

https://github.com/TBD54566975/developer.tbd.website/issues/442#issuecomment-1536600773

**Comment by EbonyLouis** [comment]
@dayhaysoos we might just need kirah to make it pretty, maybe we just need to add color like the boxes on the docs home page? like you said play around and send screenshots

**Comment by ALRubinger** [comment]
> @ALRubinger I'm not sure if that makes for the best docs experience. Normally, those types of pop ups are designed for marketing or sales engagements and I personally feel like I'd be annoyed by seeing something like that floating on the page.

I agree!

**Review by EbonyLouis — APPROVED** [review]

**Comment by EbonyLouis** [comment]
@dayhaysoos just looked at the preview its way too big lol

**Comment by ALRubinger** [comment]
Starting to come together!

Margin looks like it extends past the margin on pieces above it?

image

**Comment by ALRubinger** [comment]
Will need to rebase atop `phase-4` to see the true latest and prepare for clean merge

**Review by EbonyLouis — APPROVED** [review]

**Comment by dayhaysoos** [comment]
I'm pretty sure this is good to go! We can open up new issues for improvements moving forward

**Pull request merged**
