### PR TITLE
tbdocs: generated docs tbdocs_tbdex-js_protocol_v0.1.2

### PR DESCRIPTION
**Pull request by leordev**
Automatic generated docs from the source code in the repository [TBD54566975/tbdex-js](https://github.com/TBD54566975/tbdex-js)

Project source path: **packages/protocol**

**Please use this PR for previewing and reviewing purposes only. 
DO NOT TOUCH this PR, since it will be updated automatically by the tbdocs pipeline. 
Instead, update the docs in the source code.**

---
_Updated @ 2023-09-29T03:08:56.959Z from GH-Action Execution #NaN-NaN_

### CODE REVIEW

**Comment by leordev** [comment]
Still a draft but pretty cool results here: https://deploy-preview-765--tbd-website-developer.netlify.app/docs/tbdex-js/api-reference/protocol/

**Comment by angiejones** [comment]
good stuff! can we move it up in the nav bar? would it be possible to put it under a folder?

**CURRENT**
image

**PROPOSED** (where tbdex-js would be shown under tbDEX SDK
image

**Comment by leordev** [comment]
> good stuff! can we move it up in the nav bar? would it be possible to put it under a folder?
> 
> **CURRENT** (img)
> 
> **PROPOSED** (img)

100% -- I still need to add some polishing, a default front matter for these files etc.

**Comment by dayhaysoos** [comment]
@leordev  we talked about the results from this not being indexed by algolia. Would you like for me to make a separate issue for us to tackle that together later? Maybe this week?

**Comment by leordev** [comment]
> @leordev we talked about the results from this not being indexed by algolia. Would you like for me to make a separate issue for us to tackle that together later? Maybe this week?

100% Nick! Thanks for tracking it for us!

**Comment by leordev** [comment]
@angiejones I addressed your suggestions on our new pr! #796

**Pull request closed without merging**
