### PR TITLE
added section on Nested Types to Protocols guide

### PR DESCRIPTION
**Pull request by angiejones**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205454496787932

### CODE REVIEW

**Review by shamilovtim — APPROVED** [review]
It looks right based on my experience but I'd ask @diehuxx for a closer eye on the objects themselves to make sure I understood it correctly

**Comment by angiejones** [comment]
> It looks right based on my experience but I'd ask @diehuxx for a closer eye on the objects themselves to make sure I understood it correctly

ok thanks so much!

**Comment by angiejones** [comment]
@csuwildcat this is the PR specifically for the Nested Types part of the Protocol doc. It's based on [this convo](https://discord.com/channels/937858703112155166/1149381742210334821/1152287538967494706). Here's a [deploy preview](https://deploy-preview-740--tbd-website-developer.netlify.app/docs/web5/learn/protocols#nested-types).

**Comment by csuwildcat** [comment]
@angiejones we should have a specific convo on this, because the entire section is not reflective of the API's form or intent. I think there is just a misunderstanding, and what's on the site is actually more complex than what the Protocol structures do.

**Pull request merged**
