### PR TITLE
Fixing the sidebar in the create credentials

### PR DESCRIPTION
**Pull request by philling1**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

fixes this issue: #828 . 

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by philling1** [comment]
could you help me to review this PR also. thank you

**Comment by philling1** [comment]
Yh but I don't know how to use the codesandbox and is not the same issue but another one that I don't know why it came up

**Comment by philling1** [comment]
i really don't know how to resolve this I have tried so many things

**Comment by EbonyLouis** [comment]
@philling1 let me help, I'll play around and see if I can figure it out

**Comment by EbonyLouis** [comment]
@philling1 when I test it locally, your changes does seem to fix it. I'm not sure why the preview isn't reflecting that

**Review by angiejones — APPROVED** [review]

**Comment by dayhaysoos** [comment]
Not sure what happened but I took care of the merge conflict

**Comment by EbonyLouis** [comment]
@philling1 Good Job 🥳

**Pull request merged**
