### PR TITLE
Accessibility for markdown files

### PR DESCRIPTION
**Pull request by mishmanners**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Add accessibility features based on: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/

I also checked every other markdown file in the main folder and they all seem fine :heart: 

## Related Tickets & Documents

NA

## Mobile & Desktop Screenshots/Recordings

NA

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 readme
- [x] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

NA - documentation itself was updated

## [optional] Are there any post-deployment tasks we need to perform?

NA

## [optional] What gif best describes this PR or how it makes you feel?

NA

### CODE REVIEW

**Comment by angiejones** [comment]
heyyy Mish!

**Review by angiejones — APPROVED** [review]

**Comment by angiejones** [comment]
@EbonyLouis hacktoberfest

**Comment by angiejones** [comment]
thanks so much, @mishmanners! 🙌🏾

**Comment by mishmanners** [comment]
Heyyyyy @angiejones! Thanks for accepting my PR :smile:

**Pull request merged**
