### PR TITLE
Create Your Own Blog About Protocol Roles

### LINKED ISSUE #1807: Create Your Own Blog About Protocol Roles (2)
# Create Your Own Blog About Protocol Roles

## 🚀 Goal
We want you to share what you've learned about protocol roles in your own blog post.

## 🤔 Background
This issue focuses specifically on creating a blog post to teach others about [Web5 protocol roles](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles). Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Web5 Protocol Roles Guide](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles)
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

### PR DESCRIPTION
**Pull request by Lymah123**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [x] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Resolves #1807

## Related Tickets & Documents

Resolves #

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
Thank you for your contribution, Lymah! I have a clarifying question -- uhh the prompt was about protocol roles (a feature of protocols), but you wrote about the role protocols play. Is the documentation on protocol roles confusing?

**Review by blackgirlbytes — APPROVED** [review]
🎉

**Comment by Lymah123** [comment]
> Thank you for your contribution, Lymah! I have a clarifying question -- uhh the prompt was about [protocol roles](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles) (a feature of protocols), but you wrote about the role protocols play. Is the documentation on protocol roles confusing? @Lymah123

Hi @blackgirlbytes , I read the resources linked to the issues but I guessed my blog post diverged from the keyword which is "feature " not "roles"  

Is there a way to make correction to that?  If I can, I will go over the documentation again. 

Thanks!

**Comment by blackgirlbytes** [comment]
yeah feel free to update the blog post if you want. To be clear, I'm trying to say that..you wrote about:
- how protocols fit into decentralized systems and what part they play
- whereas protocols have a feature called Roles which allow people to say I want to give Lymah123 the role of contributor and she can only write and code in my DWN, but I'll give blackgirlbytes the role of reviewer and she can write, update, delete code in my DWN. 
That's what this documentation is getting at: https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles

**Comment by Lymah123** [comment]
Alright @blackgirlbytes 

I will update the blog post and update you so you can check it out. 

Thank you so much for the additional information and clarification

**Comment by Lymah123** [comment]
Hi @blackgirlbytes, can you check this update I made and let me know your view https://dev.to/lymah/the-role-of-protocols-in-decentralized-systems-3l9f

Thanks

**Pull request merged**
