### PR TITLE
[Oct 2024] Innovator Showcase Update

### PR DESCRIPTION
**Pull request by taniashiba**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [x] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR updates the Innovators Showcase on the community page with the following changes:

✅ Added Sondreb's Ariton
✅ Added Sondreb's BlockCore Wallet
✅ Added MyKin.AI
🚫 removed Rizel's time management app

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by blackgirlbytes — COMMENTED** [review]
did we want to include anymore and remove some? For example, you can remove mine time management app. I think it's buggy loll.

And we can even add sondreb's project called Ariton 🤷🏿‍♀️

**Comment by blackgirlbytes** [comment]
Another one that we could include is Kin -- https://mykin.ai/

**Comment by taniashiba** [comment]
> did we want to include anymore and remove some? For example, you can remove my time management app. I think it's buggy loll. And it's been up for a year +.
> 
> And we can even add sondreb's project called Ariton 🤷🏿‍♀️

I had Ariton on my list! I didn't realize it had a site https://ariton.app/ Will add!

**Comment by taniashiba** [comment]
> Another one that we could include is Kin -- https://mykin.ai/

thank you! and we do wanna remove any we don't want. lemme make changes c: tysm!!

**Comment by taniashiba** [comment]
Removed Rizel's time management app & added 2 additional apps listed above!

**Pull request merged**
