### PR TITLE
Create Your Own Blog About Protocol Roles

### LINKED ISSUE #1612: Create Your Own Blog About Protocol Roles
# Create Your Own Blog About Protocol Roles

## 🚀 Goal
We want you to share what you've learned about protocol roles in your own blog post.

## 🤔 Background
This issue focuses specifically on creating a blog post to teach others about [Web5 protocol roles](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles). Your contribution here will help developers learn about this topic!

## 🤝 How You Can Contribute
We've broken it down into smaller tasks. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
- [ ] You must host your content on your own website or channel.
- [ ] Add your content information directly to the `site/src/externalContributors.json` file in the repository.
- [ ] Save your image in the `site/static/image/external-contributor/` directory, ensuring the image is in a **16:9 ratio**.
- [ ] Create a pull request with your changes for review.
- [ ] Link your submitted PR in a comment here to count towards Hacktoberfest.

Your contribution in `externalContributors.json` must include:
- [ ] Type: Video, Blog, Social (please choose the appropriate one)
- [ ] Thumbnail: the path to your image, e.g., `/img/external-contributor/yourimage.png`
- [ ] Title: the title of your content
- [ ] Link: a direct link to your content
- [ ] Your name

Here’s an example of the JSON format to follow:

```json
[
    {
        "type": "blog",
        "thumbnail": "/img/external-contributor/yourimage.png",
        "title": "Exploring Web5",
        "link": "https://linktoyourcontent.com/web5-post",
        "contributor": "Your Name"
    }
]
```

Available `type` options:
- Video
- Blog
- Social

## 🌟 Resources
- [ ] [Web5 Protocol Roles Guide](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles)
- [ ] [Our Blogs](https://developer.tbd.website/blog/)
- [ ] [Our YouTube channel](https://www.youtube.com/@tbd.videos)

## Getting Started
This content task is part of Hacktoberfest! We welcome contributions from creators of all skill levels. Here's how you can get started:

1. Read the [contribution guidelines](#)
2. Read the [code of conduct](#)
3. Choose a content-specific task from the list above
4. Comment ".take" on the corresponding issue to get assigned the task
5. Fork the repository and create a new branch for your work
6. Make your changes and submit a pull request
7. Wait for review and address any feedback

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

### PR DESCRIPTION
**Pull request by KiranBaliga**
Closes #1612 

This PR has been raised to address the issue or task titled "Create your own blog about protocol rules".

The instructions have been followed as stated.

Please review the PR and action accordingly.

Your feedback is highly appreciated.

### CODE REVIEW

**Comment by blackgirlbytes** [comment]
Heyyy love the blog post, but did you check the resources we left for you in the resource section of the issue? 

Requestor, Mediator, Responder, Verifier, and Issuer are NOT protocol roles. 

Instead, we have `anyone`, `author`, and `recipient` and then you can make your own custom roles.

We put a link to how protocol roles work --- 

[Protocols](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-protocols)
[Protocol Roles](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles)
[Video on Protocols](https://www.youtube.com/watch?v=Wh5Cndgcc_E)

It's really important that you look at the resources, so that we will be able to feature your work

**Review by blackgirlbytes — CHANGES_REQUESTED** [review]
Heyyy love the blog post, but did you check the resources we left for you in the resource section of the issue? 

Requestor, Mediator, Responder, Verifier, and Issuer are NOT protocol roles. 

Instead, we have `anyone`, `author`, and `recipient` and then you can make your own custom roles.

We put a link to how protocol roles work --- 

[Protocols](https://developer.tbd.website/docs/web5/decentralized-web-nodes/what-are-protocols)
[Protocol Roles](https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles)
[Video on Protocols](https://www.youtube.com/watch?v=Wh5Cndgcc_E)

It's really important that you look at the resources, so that we will be able to feature your work  @KiranBaliga

**Review by blackgirlbytes — CHANGES_REQUESTED** [review]
I saw you made some updates. they're looking really good. if u could pleaseeee include information about custom roles like creating, assigning, and using roles..that would be much appreciated.

https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles

thank you!

**Review by blackgirlbytes — CHANGES_REQUESTED** [review]
I saw you made some updates. they're looking really good. if u could pleaseeee include information about custom roles like creating, assigning, and using roles..that would be much appreciated.

https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles

thank you!

**Comment by KiranBaliga** [comment]
> I saw you made some updates. they're looking really good. if u could pleaseeee include information about custom roles like creating, assigning, and using roles..that would be much appreciated.
> 
> https://developer.tbd.website/docs/web5/decentralized-web-nodes/protocol-roles
> 
> thank you!

I have made some changes..Please review.

**Comment by ALRubinger** [comment]
Attempting to close and reopen to retrigger Netlify deploy preview

**Comment by blackgirlbytes** [comment]
Hi @KiranBaliga! For some reason, the test to build your PR is not running. Do you mind closing this PR and reopening another one? I want to see if we can retrigger that build, so I will be able to merge your PR.

Thank you!

**Comment by KiranBaliga** [comment]
Closing this PR aa instructed.

**Pull request closed without merging**
